<?php
__( 'Red', 'stream-player' );
__( 'Orange', 'stream-player' );
__( 'Yellow', 'stream-player' );
__( 'Light Green', 'stream-player' );
__( 'Green', 'stream-player' );
__( 'Cyan', 'stream-player' );
__( 'Light Blue', 'stream-player' );
__( 'Blue', 'stream-player' );
__( 'Purple', 'stream-player' );
__( 'Magenta', 'stream-player' );
__( 'Stream Player needs to be installed and activated to use %s.', 'stream-player' );
__( 'Activate Stream Player', 'stream-player' );
__( 'Install Stream Player', 'stream-player' );
__( 'Your Stream Player plugin needs to updated to work with %s.', 'stream-player' );
__( 'The required minimum version of the Stream Player plugin is:', 'stream-player' );
__( 'Update Stream Player', 'stream-player' );
__( 'Settings', 'stream-player' );
__( 'Extending', 'stream-player' );
__( 'with', 'stream-player' );
__( 'Stream Player Pro', 'stream-player' );
__( 'You have both Radio Station Pro and Stream Player Pro activated!', 'stream-player' );
__( 'Please visit your Plugins page to disable one or the other.', 'stream-player' );
__( 'Important: %s continuous player bar is active.', 'stream-player' );
__( 'This overrides the page fade in, load timeout and loader bar settings here.' );
__( 'Adjust those settings via your Radio Station settings page instead.', 'stream-player' );
__( '"%1$s" require "%2$s" to be installed and activated.', 'radio-station' );
__( 'Stream Player Elementor Widgets', 'radio-station' );
__( 'Elementor', 'radio-station' );
__( '"%1$s" require "%2$s" version %3$s or greater.', 'radio-station' );
__( 'PHP', 'radio-station' );
__( 'Stream Player', 'radio-station' );
__( 'Metadata Source', 'stream-player' );
__( 'Default Plugin Setting', 'stream-player' );
__( 'Override: Metadata On', 'stream-player' );
__( 'Override: Metadata Off', 'stream-player' );
__( 'Override: Metadata URL', 'stream-player' );
__( 'Override: Current Playlist', 'stream-player' );
__( 'Metadata Override URL', 'stream-player' );
__( 'Color Options', 'stream-player' );
__( 'Player Text Color', 'stream-player' );
__( 'Player Background Color', 'stream-player' );
__( 'Playing Color', 'stream-player' );
__( 'Buttons Color', 'stream-player' );
__( 'Track Color', 'stream-player' );
__( 'Track Thumb Color', 'stream-player' );
__( 'Advanced Options', 'stream-player' );
__( 'Popup Player Button', 'stream-player' );
__( 'Plugin Setting', 'stream-player' );
__( 'On', 'stream-player' );
__( 'Off', 'stream-player' );
__( 'Current Show Display', 'stream-player' );
__( 'Now Playing Track Display', 'stream-player' );
__( 'Track Animation', 'stream-player' );
__( 'No Animation', 'stream-player' );
__( 'Left to Right Ticker', 'stream-player' );
__( 'Right to Left Ticker', 'stream-player' );
__( 'Back and Forth', 'stream-player' );
__( 'Metadata URL', 'stream-player' );
__( 'Leave blank to use stream URL.', 'stream-player' );
__( 'Custom Theme', 'stream-player' );
__( 'Popup Player to separate window.', 'stream-player' );
__( 'Popup Player', 'stream-player' );
__( 'Stream Player', 'stream-player' );
__( 'Stream Player Audio stream player module.', 'stream-player' );
__( 'General', 'stream-player' );
__( 'Player Content', 'stream-player' );
__( 'Stream URL', 'stream-player' );
__( 'Leave blank to use default stream.', 'stream-player' );
__( 'Player Title Text', 'stream-player' );
__( 'Empty for default, 0 for none.', 'stream-player' );
__( 'Player Station Image', 'stream-player' );
__( 'Display Station Image', 'stream-player' );
__( 'Do Not Display Station Image', 'stream-player' );
__( 'Player Options', 'stream-player' );
__( 'Player Script', 'stream-player' );
__( 'Amplitude', 'stream-player' );
__( 'Howler', 'stream-player' );
__( 'jPlayer', 'stream-player' );
__( 'Initial Volume', 'stream-player' );
__( 'Volume Controls', 'stream-player' );
__( 'Volume Slider', 'stream-player' );
__( 'Up and Down Buttons', 'stream-player' );
__( 'Mute Button', 'stream-player' );
__( 'Maximize Button', 'stream-player' );
__( 'Use as Default Player', 'stream-player' );
__( 'Make this the default player on this page.', 'stream-player' );
__( 'No', 'stream-player' );
__( 'Yes', 'stream-player' );
__( 'None', 'stream-player' );
__( 'Metadata Source URL', 'stream-player' );
__( 'Defaults to Stream URL.', 'stream-player' );
__( 'Player Design', 'stream-player' );
__( 'Player Layout', 'stream-player' );
__( 'Vertical (Stacked', 'stream-player' );
__( 'Horizontal (Inline', 'stream-player' );
__( 'Player Theme', 'stream-player' );
__( 'Light', 'stream-player' );
__( 'Dark', 'stream-player' );
__( 'Player Buttons', 'stream-player' );
__( 'Circular', 'stream-player' );
__( 'Rounded', 'stream-player' );
__( 'Square', 'stream-player' );
__( 'Style', 'stream-player' );
__( 'Container Styles', 'stream-player' );
__( 'Alignment', 'stream-player' );
__( 'Player Colors', 'stream-player' );
__( 'Background Color', 'stream-player' );
__( 'Playing Highlight Color', 'stream-player' );
__( 'Buttons Highlight Color', 'stream-player' );
__( 'Slider Track Color', 'stream-player' );
__( 'Slider Thumb Color', 'stream-player' );
__( 'Typography', 'stream-player' );
__( 'Player Typography', 'stream-player' );
__( 'Station Text Color', 'stream-player' );
__( 'Station Typography', 'stream-player' );
__( 'Show Text Color', 'stream-player' );
__( 'Show Typography', 'stream-player' );
__( 'Song Track Text Color', 'stream-player' );
__( 'Song Track Typography', 'stream-player' );
__( 'Player Alignment', 'stream-player' );
__( 'Left', 'stream-player' );
__( 'Center', 'stream-player' );
__( 'Right', 'stream-player' );
__( 'Station Text Typography', 'stream-player' );
__( 'Show Text Typography', 'stream-player' );
